# Generated by Django 4.1.2 on 2022-10-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('RoundId', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('EnrollmentNo', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=300)),
                ('EmailId', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=300)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SectionId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('RId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.round')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='S_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.season'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionId', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=500)),
                ('QuestionType', models.CharField(max_length=250)),
                ('ModelAnswer', models.CharField(max_length=1000)),
                ('TotalMarks', models.IntegerField()),
                ('SeId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.section')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('EvaluatorId', models.IntegerField(primary_key=True, serialize=False)),
                ('PanelId', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('SId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.season')),
                ('UserId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('StudentId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('EnrollmentNo', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('EmailId', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('cg', models.FloatField()),
                ('RId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.round')),
                ('SId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.season')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('AnswerGiven', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('QuestionId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.question')),
                ('studentId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSlot', models.CharField(max_length=250)),
                ('EvaluationStatus', models.CharField(max_length=250)),
                ('RoundStatus', models.CharField(max_length=250)),
                ('RoundId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.round')),
                ('candidateId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.candidates')),
            ],
        ),
    ]
