# Generated by Django 4.1.2 on 2022-10-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer')], max_length=250),
        ),
        migrations.AlterField(
            model_name='round',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer')], max_length=300),
        ),
    ]
