# Generated by Django 4.1.2 on 2022-10-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_candidates_role_alter_round_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_round',
            name='EvaluationStatus',
            field=models.CharField(choices=[('evaluated', 'Evaluated'), ('not evaluated', 'not evaluated'), ('qualified', 'qualified'), ('not qualified', 'not qualified'), ('called', 'called'), ('not called', 'not called')], max_length=250),
        ),
    ]
