# Generated by Django 4.1.2 on 2022-10-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_candidate_round_evaluationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='S_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='round_season', to='backend.season'),
        ),
    ]
