# Generated by Django 4.1.2 on 2022-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_round_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='status',
            field=models.CharField(default='Registered', max_length=250),
        ),
    ]
