# Generated by Django 4.1.2 on 2022-10-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_candidates_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='SId',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.season'),
        ),
    ]
