# Generated by Django 4.1.2 on 2022-11-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('designer', 'Designer')], max_length=300, null=True),
        ),
    ]
