# Generated by Django 4.1.2 on 2022-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='EmailId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
